group/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import include
#from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
from django.conf.urls import url
# from .import index

#from .api import UserList, UserDetail, UserAuthentication

urlpatterns = [
    path('MainGroup.html', views.mainGroup, name="MainGroup"),
    path('group.html', views.group, name="Group"),
    path('MyGroup.html',views.myGroup, name="MyGroup"),
    path('CreategroupAdmin.html',views.GroupAdmin, name="GroupAdmin"),
    path('EditGroup.html',views.updateGroup, name="updateGroup"),
 

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

igrowKMS/urls.py
from django.contrib import admin, auth
from rest_framework.routers import DefaultRouter
from django.urls import path, include
#from .import views
from django.conf.urls import url, include
from rest_framework import authentication
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # path('',views.Indexpage),
    path('', include('member.urls')),
    path('', include('group.urls')),
    path('', include('sharing.urls')),
    path('', include('workshop.urls')),
    #path('auth/', include('auth.urls')),
    #path('api/', include('member.urls')),
]

member/urls.py
from django.urls import path
from django.conf.urls import url, include
#from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import authentication
from rest_framework_simplejwt.views import TokenRefreshView

from group.views import updateGroup
#from .views import MyObtainTokenPairView, user_list
from rest_framework.authtoken.views import obtain_auth_token
from member.api import UserAuthentication, UserList
#from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
from .import api
from django.conf.urls import url
# from .import index
#from member import views
#from rest_framework import routers

#router = routers.DefaultRouter(trailing_slash=False) 
#router.register('Userdetails', views.Users)


urlpatterns = [

    #url(r'^admin/', admin.site.urls),
    #url(r'^$',views.signIn, name="SignIn"),
    #url('sign',views.signUp),
    #path('registration.html',views.signUp, name="signUp"),
    url('^postsign/',views.postsign),
    path('',views.Indexpage),
    path('Home',views.homepage, name="Home"),
    path('HomeAdmin',views.homepageAdmin, name="HomeAdmin"),
    path('Registration', views.UserReg, name="Reg"),
    path('Loginpage', views.loginpage, name="Loginpage"),
    path('Logout',views.logout, name="Logout"),
    path('View',views.view,name="View"),

    path('MainSharing.html',views.mainSharing, name="MainSharing"),
    path('sharing.html/<str:fk1>/',views.sharing, name="Sharing"),
    #path('ViewSharing',views.viewSharing,name="ViewSharing"),
    path('ViewSharing.html/<str:fk1>/',views.updateSharing, name="UpdateSharing"),
    path('DeleteSharing.html/<str:fk1>/', views.deleteSharing, name="DeleteSharing"),

    path('MainGroup.html',views.mainGroup, name="MainGroup"),
    path('group.html/<str:fk1>/',views.group, name="Group"),
    path('MyGroup.html',views.myGroup, name="MyGroup"),
    path('CreategroupAdmin.html',views.GroupAdmin, name="GroupAdmin"),
    #path('CreategroupAdmin.html',views.GroupAdmin, name="GroupAdmin"),
    path('EditGroup.html/<str:fk1>/<str:fk>/',views.updateGroup, name="EditGroup"),
    #path('EditGroup.html',views.ViewEditGroup, name="ViewEditGroup"),
    #url(r'^world/(?P<world_pk>\d+)/(?P<country_pk>\d+)/$'
    
    path('AddGroupSharing.html/<str:fk1>/<str:fk3>/', views.GSharing, name="GSharing"),
    path('ViewGroupSharing.html/<str:fk1>/', views.ViewGroupSharing, name="ViewGroupSharing"),
    path('EditGroupSharing.html/<str:fk1>/',views.updateGroupSharing, name="UpdateGroupSharing"),
    path('DeleteGroupSharing.html/<str:fk1>/', views.deleteGroupSharing, name="DeleteGroupSharing"),
    

    path('MainMember.html', views.mainMember, name="MainMember"),
    path('member.html',views.member, name="member"),
    path('friendlist.html',views.friendlist, name="friendlist"),
    #path('MyMember.html',views.myMember, name="MyMember"),
    path('MainSearchbar', views.MainSearchbar, name='MainSearchbar'),
    path('UserList', views.UserList, name="UserList"),

    path('workshop.html',views.workshop, name="Workshop"),
    path('booking.html/<str:fk1>/',views.booking, name="Booking"),
    path('CreateWorkshop.html',views.createWorkshop, name="CreateWorkshop"),
    path('BookWorkshop.html',views.BookWorkshop, name="BookWorkshop"),
    path('BookingList.html',views.BookingList, name="BookingList"),
    path('deleteWorkshop.html/<str:fk1>/',views.deleteWorkshop, name="deleteWorkshop"),
    path('deleteBooking.html/<str:fk1>/',views.deleteBooking, name="deleteBooking"),

    url(r'^api/users_lists/$', UserList.as_view(), name='user_list'),
    #url(r'^api/users_list/(?P<id>\d+)/$', UserDetail.as_view(), name='user_list'),
    url(r'^api/auth/$', UserAuthentication.as_view(), name='User Authentication API'),
    #url(r'^rest-auth/', include('rest_auth.urls')),
    #url(r'^rest-auth/registration/', include('rest_auth.registration.urls'))
    #path('login/', MyObtainTokenPairView.as_view(), name='token_obtain_pair'),
    #path('login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    #path('userlist/', views.user_list, name='userlist'),
    #path('login', obtain_auth_token, name='login')
    path('users/login/', api.login_user, name='login'),
    path('users/token/<pk>', api.getUserFromToken, name='user-token'),
    

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

member/models.py
from django import db
from django.db import models, migrations
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib.syndication.views import Feed

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from ast import Pass
from django.db import models
from django.contrib.auth.models import User
#import firebase_admin
#from firebase_admin import credentials
#from firebase_admin import firestore

#cred = credentials.Certificate('D:\IGROW_V-main\member\serviceAccountKey.json')

#firebase_admin.initialize_app(cred, {
#    'databaseURL': 'https://i-grow-kmma.firebaseio.com'
#})


class Person(models.Model):
    Email = models.CharField(max_length=150, unique=True)
    # Pwd = models.CharField(max_length=150)
    Password = models.CharField(max_length=150)
    Username = models.CharField(max_length=150)
    Name = models.CharField(max_length=150)
    DateOfBirth = models.CharField(max_length=150)
    Age = models.IntegerField ()
    District = models.CharField(max_length=150)
    State = models.CharField(max_length=150)
    Occupation = models.CharField(max_length=150)
    About = models.CharField(max_length=150)
    Gender = models.CharField(max_length=1)
    MaritalStatus = models.CharField(max_length=150)
    UserLevel = models.CharField(max_length=10)
    Photo = models.ImageField(upload_to ='images/')
    #resume = models.ImageField(null=True, blank=True)

    @property
    def is_anonymous(self):
   
        return False
    @property
    def is_authenticated(self):
   
        return False

    def save(self):
        super().save()
        super().save(using='farming')

    class Meta:
        db_table = 'login_person'
        #db.collection('login_person')

        #fields = ['Email', 'Password']
    
    USERNAME_FIELD = 'Email'
    REQUIRED_FIELDS = ['username']
        
def user_form(sender, instance, created, **kwargs):
    if created:
        Person.objects.create(user=instance)
        instance.Person.save()

class Member(models.Model):
    class Meta:
        db_table = 'Member'
    Name = models.CharField(max_length=150)
    Study = models.CharField(max_length=1000)
    Lives = models.CharField(max_length=1000)
    


class SensorData(models.Model):
    class Meta:
        db_table = 'SensorData'    
    Detail = models.CharField(max_length=255)
    Name = models.CharField(max_length=150)

class Plants(models.Model):
    class Meta:
        db_table = 'Plants'
    Pictures = models.ImageField(upload_to='uploads/')
    Species = models.CharField(max_length=150)
    Types = models.CharField(max_length=150)


class Users(models.Model):
    class Meta:
        db_table = 'Users'
    username = models.CharField(max_length=10, unique=True) #AI190201
    password = models.CharField(max_length=30) #ninja saga
    name = models.CharField(max_length=100) #FAIZ BIN AB. HAMID
    age = models.IntegerField() #22
    ranking = models.FloatField() #2.5

    def upload_photo(self, filename):
        path = 'member/photo/{}'.format(filename)
        return path

    photo = models.ImageField(upload_to=upload_photo, null=True, blank=True)

    def upload_file(self, filename):
        path = 'member/file/{}'.format(filename)
        return path

    resume = models.ImageField(upload_to=upload_file, null=True, blank=True)

    def __str__(self):
        return f"{self.Username} - {self.Password}"

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

member/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from .models import Person, Feed
from .models import *

class PersonForm(forms.ModelForm):
    class Meta:  
        model = Person 
        fields = "__all__"  

class UserUpdateForm(forms.ModelForm):
    Username = forms.CharField(required=True)
    Email = forms.EmailField(required=True)
    Name = forms.CharField(required=False)
    DateOfBirth = forms.CharField(required=False)
    Age = forms.CharField(required=False)
    District = forms.CharField(required=False)
    State = forms.CharField(required=False)
    Occupation = forms.CharField(required=False)
    About = forms.CharField(required=False)
    Gender = forms.CharField(required=False)
    MaritalStatus = forms.CharField(required=False)

    class Meta:
        model = Person
        fields = ['Email','Password','Username','Name','DateOfBirth','Age','District','State','Occupation','About','Gender','MaritalStatus']



class UserDeleteForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = []


class SharingForm(forms.ModelForm):
    class Meta:
        model = Feed
        fields = '__all__'

class CreateInDiscussion(ModelForm):
    class Meta:
        model= Group
        fields = '__all__'

member/templates/UserList.html
<!doctype html>
<html lang="en">
<head></head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<h1 class="p-3 mb-2 bg-success text-white text-center">iGROW Knowledge Management System</h1>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

<b>
  <div>
    <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist" >
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="{% url 'HomeAdmin' %}" role="tab" aria-controls="home" aria-selected="true">Home</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="sharing-tab" data-bs-toggle="tab" href="{% url 'UserList' %}" role="tab" aria-controls="sharing" aria-selected="true">User</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="discussion-tab" data-bs-toggle="tab" href="{% url 'GroupAdmin' %}" role="tab" aria-controls="discussion" aria-selected="true">Group</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="discussion-tab" data-bs-toggle="tab" href="" role="tab" aria-controls="discussion" aria-selected="true">Booking</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="workshop-tab" data-bs-toggle="tab" href="{% url 'Workshop' %}" role="tab" aria-controls="workshop" aria-selected="true">Workshop</a>
       </li>
      </li>
    </ul>
  </div>
<br/>
<br/>
<br/>
<p class="h3 text-center align-content: center;">User List</p><br/>
  
  <form method="POST" class="container text-left">
    {% csrf_token %}
    <form class="row g-3">
      {% csrf_token %}
      
      
        <div class="container">
            <div class="row">
              <table class="table caption-top">
                <thead>
                  <tr>
                    <th scope="col">Username</th>
                    <th scope="col">Name</th>
                    <th scope="col">Password</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for person in person %}
                    {% if person.UserLevel %}
                    {% if 'user' %}
                    
                  <tr>
                    <th scope="row" value="{{ person.Username }}">{{ person.Username }}</th>
                    <th scope="row" value="{{ person.Name }}">{{ person.Name }}</th>
                    <th scope="row" value="{{ person.Password }}">{{ person.Password }}</th>
                    <td>
                    <button type="submit" class="btn btn-success " value="View">View</button>
                    </td>
                </tr>
                <br/>
                {% endif %}                   
        {% endif %}
       {% csrf_token %}
       {% endfor %}
                </tbody>
              </table>


      <!-- <div class="col-md-4">
        <label for="id_Username" class="form-label">Username : </label>
        <input type="text" name="Name" value="{{ person.Username }}" class="vTextField" maxlength="150" required="" id="id_Name">
       </div>
      <div class="col-md-4">
       <label for="id_Name" class="form-label">Name : </label>
       <input type="text" name="Name" value="{{ person.Name }}" class="vTextField" maxlength="150" required="" id="id_Name">
      </div>
       <div class="col-12">
        <label for="id_Password" class="form-label">Password: </label>
        <input type="text" name="About" value="{{ person.Password }}"  class="vTextField" maxlength="150" required="" id="id_Password">
       </div>
      </div> -->
        <br/>
        
     </div>
     <br/><br/>
     {% if messages %}
     {% for msg in messages %}
     <b>{{msg}}</b>
     {% endfor %}
     {% endif %}
     <br/><br/>
   </form>
  </form>
<hr/>
</html>

member/templates/profile.html
<!doctype html>
<html lang="en">
<head>
    <style>
      .content {
        max-width: 500px;
        margin: auto;
                }
      form{
        border:4px solid black;
        margin: 0 auto;
        padding: 60px;
        width: fit-content;
          }
      img {
      border-radius: 50%;
        }
    </style>
</head>
  
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

   <h1 class="p-3 mb-2 bg-success text-white text-center">iGROW Knowledge Management System</h1>

   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
   <script>
    </script>
    <b>
      <div>
        <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist" >
          <li class="nav-item" role="presentation">
            <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="{% url 'Home' %}" role="tab" aria-controls="home" aria-selected="true">Home</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link active" id="sharing-tab" data-bs-toggle="tab" href="{% url 'MainSharing' %}" role="tab" aria-controls="sharing" aria-selected="true">Sharing</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link active" id="discussion-tab" data-bs-toggle="tab" href="{% url 'MainGroup' %}" role="tab" aria-controls="discussion" aria-selected="true">Group</a>
          </li>
          <li class="nav-item" role="presentation">
           <a class="nav-link active" id="friends-tab" data-bs-toggle="tab" href="{% url 'MainMember' %}" role="tab" aria-controls="friends" aria-selected="true">Member</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link active" id="workshop-tab" data-bs-toggle="tab" href="{% url 'BookWorkshop' %}" role="tab" aria-controls="workshop" aria-selected="true">Workshop</a>
           </li>
           <li class="nav-item" role="presentation">
            <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="{% url 'View' %}" role="tab" aria-controls="profile" aria-selected="true">Profile</a>
           </li>
          </li>
        </ul>
      </div>
    <br/>
 
      <h1 class="margin-left text-center">Profile</h1>
     
<form class="form-horizontal" method="POST" ><input type="hidden" name="csrfmiddlewaretoken" value="LUo8yACYeqTzOUYPx81ouuqmkcDTGHdxJkRjbmc5wCVtI7LYrhK5sUxWg2LWIEWX">
  
  {% csrf_token %}
  {% for person in person %}
  <div>
    <img src="media/{{ person.Photo }}" width="300" height="300">
  </div><br>
      <div class="form-row field-Email mb-3 row">
      
      
        <div>
          <label class="required" for="id_Email">Email:</label>
            <input type="text" name="Email" value="{{ person.Email }}"  class="vTextField" maxlength="150" required="" id="id_Email">
        </div>
      </div>
      <div class="form-row field-Password mb-3 row">
        <div>
        <label class="required" for="id_Password">Password:</label>
            <input type="text" name="Password" value="{{ person.Password }}" class="vTextField" maxlength="150" required="" id="id_Password">
        </div>
      </div>
      <div class="form-row field-Username mb-3 row">
        <div>
        <label class="required" for="id_Username">Username:</label>
            <input type="text" name="Username" value="{{ person.Username }}" class="vTextField" maxlength="150" required="" id="id_Username">
        </div>
      </div>
      <div class="form-row field-Name mb-3 row">
        <div>
        <label class="required" for="id_Name">Name:</label>
            <input type="text" name="Name" value="{{ person.Name }}" class="vTextField" maxlength="150" required="" id="id_Name">
          </div>
      </div>
      <div class="form-row field-DateOfBirth mb-3 row">
        <div>
          <label class="required" for="id_DateOfBirth">Date Of Birth:</label>
            <input type="text" name="DateOfBirth" value="{{ person.DateOfBirth }}" class="vTextField" maxlength="150" required="" id="id_DateOfBirth">
        </div>
      </div>
      <div class="form-row field-Age mb-3 row">
        <div>
          <label class="required" for="id_Age">Age:</label>
            <input type="number" name="Age" value="{{ person.Age }}" class="vIntegerField" required="" id="id_Age">
        </div>
      </div>
      <div class="form-row field-District mb-3 row">                       
        <div>        
          <label class="required" for="id_District">District:</label>
            <input type="text" name="District" value="{{ person.District }}" class="vTextField" maxlength="150" required="" id="id_District">
        </div>
      </div>
      <div class="form-row field-State mb-3 row">                                                                                                               
      <div>                                                           
          <label class="required" for="id_State">State:</label>
            <input type="text" name="State" value="{{ person.State }}" class="vTextField" maxlength="150" required="" id="id_State">                                                                                                                  
        </div>
      </div>
      <div class="form-row field-Occupation mb-3 row">
        <div>
          <label class="required" for="id_Occupation">Occupation:</label>
          <input type="text" name="Occupation" value="{{ person.Occupation }}" class="vTextField" maxlength="150" required="" id="id_Occupation">
        </div>
      </div>
      <div class="form-row field-About mb-3 row">
        <div>
          <label class="required" for="id_About">About:</label>
            <input type="text" name="About" value="{{ person.About }}" class="vTextField" maxlength="150" required="" id="id_About">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        </div>
      </div>
      <div class="form-row field-Gender mb-3 row">
        <div>
          <label class="required" for="id_Gender">Gender:</label>
            <input type="text" name="Gender" value="{{ person.Gender }}" class="vTextField" maxlength="1" required="" id="id_Gender">
        </div>
      </div>
      <div class="form-row field-MaritalStatus mb-3 row">
          <div>
           <label class="required" for="id_MaritalStatus">Marital Status:</label>
            <input type="text" name="MaritalStatus" value="{{ person.MaritalStatus }}" class="vTextField" maxlength="150" required="" id="id_MaritalStatus">
          </div>
      </div>
 
    {% endfor %}

    <button type="submit" class="btn btn-success" href="{% url 'View' %}">Edit</button>
    <a href="{% url 'Logout' %}" class="card-link">Logout</a>
 
</form>
</html>